# Change these first
owner: kevinbrechbuehl # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: kevinbrechbuehl.ch
    url: https://kevinbrechbuehl.ch
  - name: kevinbrechbuehl.com
    url: https://kevinbrechbuehl.com
  - name: aquasonic.ch
    url: https://aquasonic.ch
  - name: Blog
    url: https://ctor.io
  - name: My Fuel
    url: https://myfuel.ctor.io
  - name: My Home
    url: https://myhome.ctor.io
  - name: Coiffeur Cocoon
    url: https://www.coiffeur-cocoon.ch
  - name: Coiffeur Cocoon Api
    url: https://api.coiffeur-cocoon.ch
    expectedStatusCodes:
      - 403
  - name: Coiffeur Cocoon Booking
    url: https://my.calenso.com/book/coiffeur-cocoon
  - name: inrison
    url: https://www.inrison.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Status Page**"
  # introMessage: n/a
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
